// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        int64
	UserID    int64
	Balance   int64
	Currency  string
	CreatedAt pgtype.Timestamptz
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	Amount        int64
	CreatedAt     pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
